name: Build & Preview PR

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.txt'
      - '.all-contributorsrc'

defaults:
  run:
    shell: bash

permissions:
  pull-requests: write # Required to update PR status comment

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: Build Blog
        run: QUARKUS_ROQ_GENERATOR_BATCH=true mvn -B package quarkus:run

      - name: Store PR id
        id: pr
        run: echo "pr_number=${{ github.event.number }}" >> $GITHUB_OUTPUT

      - name: Publish blog to Surge.sh
        run: |
          npx surge ./target/roq --domain https://quarkusclub-blog-${{ steps.pr.outputs.pr_number }}-preview.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Comment preview URL on PR
        uses: quarkusio/action-helpers@main
        with:
          action: maintain-one-comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.pr.outputs.pr_number }}
          body: |
            🚀 PR Preview for **blog** ${{ github.sha }} has been successfully built!
            * https://quarkusclub-blog-${{ steps.pr.outputs.pr_number }}-preview.surge.sh
          body-marker: <!-- Preview status comment marker -->

      - name: Update PR status comment on failure
        if: ${{ failure() }}
        uses: actions-cool/maintain-one-comment@v3.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            😭 Deploy PR Preview failed.
            <img width="300" src="https://user-images.githubusercontent.com/507615/90250824-4e066700-de6f-11ea-8230-600ecc3d6a6b.png">
            <!-- Sticky Pull Request Comment -->
          body-include: '<!-- Sticky Pull Request Comment -->'
          number: ${{ steps.pr.outputs.id }}
          emojis: 'confused'